### ISSUE TITLE
Plugin fails to load when g:minisnip_dir is set

### ISSUE THREAD

**Issue by LkeMitchll** [joereynolds/deoplete-minisnip#2]
When the user sets `g:minisnip_dir` to something non-default in vimrc or init.vim e.g:

`let g:minisnip_dir = '~/.config/nvim/minisnip'`

Vim will display the following trace:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/Luke/.local/share/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/deoplete.
py", line 354, in load_sources
[deoplete]     source = Source(self._vim)
[deoplete]   File "/Users/Luke/.local/share/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/m
inisnip.py", line 14, in __init__
[deoplete]     self.snippets = os.listdir(str(Path.home()) + '/.vim/minisnip')
[deoplete] FileNotFoundError: [Errno 2] No such file or directory: '/Users/Luke/.vim/minisnip'
[deoplete] Could not load source: minisnip.  Use :messages for error details.
```

Note that the plugin appears to be looking for the default snippet folder (`~/.vim/minisnip`)

**Comment by joereynolds** [comment]
Yeah,

We need to check for that beforehand, I think it's a simple fix :)
Feel free to submit a PR, I'll try and address it on the weekend otherwise

**Comment by joereynolds** [comment]
Hey!

Sorry about the delay, I believe this has been fixed with https://github.com/joereynolds/deoplete-minisnip/commit/a4b517c5b1c9d3807173a7342419be44ff812728

Now, you can uncomment that line in your dotfiles ;D

**Comment by LkeMitchll** [comment]
Thanks! (https://github.com/LkeMitchll/Dotfiles/commit/884ebacb324153455404b7b2d3c8a9a0f75c1633)
